### ISSUE TITLE
projectile aimbot won't hit head on huntsman

### ISSUE THREAD

**Issue by Podssa** [Fedoraware/Fedoraware#688]
projectile aimbot won't hit head on huntsman

**Comment by lnd1g0** [comment]
I AM NOT CRAZY! I am not crazy! I know he swapped those numbers, I knew it was 1216 — one after Magna Carta, as if I could ever make such a mistake! Never, never! I just-I just couldn't prove it! H-H-He covered his tracks, he got that idiot at the copy shop to lie for him! You think this is something, you think this is bad, this, this chicanery? He's done worse. That billboard! Are you telling me that a man just happens to fall like that? No, he orchestrated it! Jimmy! HE DEFECATED TROUGH A SUNROOF! And I saved him! I shouldn't have, I took him into my own firm! What was I thinking?! He'll never change. He'll never change, ever since he was 9, always the same. Couldn't keep his hands out of the cash drawer. "But not our Jimmy, couldn't be precious Jimmy!" Stealing them blind! And he gets to be a lawyer?! What a sick joke! I should have stopped him when I had the chance! And you, you have to stop him, you—

**Comment by alakazambun** [comment]
Could you reach into your breast pocket and tell me what's there?

**Comment by lnd1g0** [comment]
you moron. you clown. you utter buffoon. the battery scene happened before chuck says that.

**Comment by alakazambun** [comment]
https://user-images.githubusercontent.com/112496740/188689032-6aab03bf-b5a5-46c7-8533-7afe34d93b9a.jpg

**Comment by johnathon-walnut** [comment]
https://user-images.githubusercontent.com/36936588/202928886-9701a8c2-b104-4506-8f0e-d025d3f108fd.mp4

works 4 me
