### ISSUE TITLE
Fast stop to strafe / change direction faster

### ISSUE THREAD

**Issue by SylveonBottle** [Fedoraware/Fedoraware#773]
fast stop noticably doesn't activate when you're strafing left/right

If the player goes from left -> right (or vice versa), we should activate fast stop for a second so that it's faster 

idk would be cool

**Comment by xxmyn** [comment]
it would be cool but i have no idea how to do it.

**Comment by SylveonBottle** [comment]
> it would be cool but i have no idea how to do it.

if player is pressing A and D at the same time, use fast-stop once (not constantly)
Same with W and S at the same time.

Pressing these two buttons causes you to stop moving anyways, so if a person presses A and then D, it should faststop one time. by then the player should've let go of A and should only be pressing S anyways, so

Idk there's probably a better way of doing this

**Comment by SylveonBottle** [comment]
You could probably check if your velocity doesn't match the direction you're pressing either?

I.e. if you're walking forward, and you press S, your velocity is going forwards but you're trying to go backwards.. so it would be faster to do a faststop

Same with strafing left and then pressing D to strafe right - While you're holding D, your velocity will be to the left momentarily. 

Doing something like this could probably also faststop if the user holds forward and turns 180. You'd fast stop and then immediately start going the direction you're facing which would be neat

**Comment by xxmyn** [comment]
i could check pcmd->sidemove and pcmd->forwardmove and do faststop when they switch (both reach from -450 to 450) from one side to the other, but if you're moving forward and strafing to the side you would be stopped which is an issue.

on another note, the movement stop method im using actually only stops your forward and backward movement, so if you were moving forward and changed your strafe direction you could simply face 90 degrees to your left or right, change your forward move to sidemove in the appropriate direction, and then continue moving at the same speed, while completely stopping your sideways movement in 1 tick, however i think this would be hard for me to add because i am a paster :D

**Comment by johnathon-walnut** [comment]
Buttons

**Comment by xDroflLOL** [comment]
buttons.

**Comment by xxmyn** [comment]
added

**Comment by SylveonBottle** [comment]
sick, works great with null-movement config

**Comment by SylveonBottle** [comment]
Actually, you could probably get bunnyhop to work with this?
Currently bunnyhop/autostrafe makes you spin in circles.. but if you're wanting to go the other way, you sorta gotta wait until you loop back around. If you took an extra few ticks to let 'fast delta strafe' to kick in, you could potentially immediately change your strafing direction.
